### ISSUE TITLE
tcpdump output does not fit in terminal [Lab 5 - Part 6]

### ISSUE THREAD

**Issue by gsoosk** [amirhakh/TCP-IP-Laboratory#17]
سلام،

در بخش ششم، سوال اول آزمایشگاه گفته شده با استفاده از خروجی
 tcpdump 
مقدار زمان ارسال هر کدام از فایل‌ها را محاسبه کنیم. 

اما متاسفانه با توجه به تعداد بلاک‌های زیاد فایل 
large.dum
تمام خروجی در ترمینال قابل مشاهده نیست و نمی‌توان زمان را محاسبه کرد. 

بهتر است یا فایل حجمش کمتر شود یا درصورت آزمایشگاه گفته شود ازوایرشارک استفاده شود. 

با تشکر

**Comment by hadisfr** [comment]
‫یک مشکل وایرشارک این بوده که کلاً زیاد استیبل نبود و خیلی پیش می‌اومد موقع کار توی آزمایش‌ها کرش کنه و بچه‌ها مجبور بشن دوباره آزمایش رو تکرار کنن یا برن سراغ `tcpdump`. مهم‌ترین دلیلی که وایرشارک صرفاً‌ معرفی شد و در ادامهٔ دستورکارها فقط از `tcpdump` استفاده شد همین بود.

‫شاید بهتر باشه توضیحاتی داده بشه که بچه‌ها با `less` یا `head` و `tail` کار کنن و بتونن خروجی `tcpdump` رو از توی فایل بخونن، اگر منظورت بخش ۷ آزمایش ۵ (UDP) توی نسخهٔ فعلی خروجی نهایی دستورکارها باشه. 🤔

**Comment by amirhakh** [comment]
با تجربه ای که در برگزاری آزمایشگاه داشته ام، `tcpdump` خیلی مطمئن تر از `wireshark`  کار مکند. البته این برای محیط `gns3` هست.
برای رفع این مشکل بهتره که خروجی `tcpdump` یا با `-w` ریخته بشه توی یک فایل و بعد از بیرون ماشین با `wireshark` باز بشه و یا این که با کمک هدایت به فایل `> output.txt` و کمک گرفتن از دستورهای `head` و یا `tail` و همچنین دو دستور `grep` و `less` در فایل جستجو انجام داد.

**Comment by amirhakh** [comment]
resolved in version 1.3.4
